### ISSUE TITLE
Firmware update ends on 3.0%

### ISSUE THREAD

**Issue by flexund** [slightech/MyntCoreBluetoothSDK#1]
I'm using an iPhone 6, iOS 10.

Updating the firmware of all my MYNT buttons always ends after the progress reaches 3.0%

Could this be due to my recent upgrade to iOS 10?

**Comment by Robin-JW** [comment]
We will check this soon, thank u

**Comment by Robin-JW** [comment]
fixed

**Comment by flexund** [comment]
Awesome!

**Comment by fantingsheng** [comment]
Awesome!
